- name: Restart NGINX Service on Failure
  hosts: localhost
  become: yes
  tasks:
    - name: Restart NGINX
      service:
        name: nginx
        state: restarted
        server {
    listen 0.0.0.0:80;
    server_name 54.166.172.182;
    }
